image:
  file: .gitpod.Dockerfile
ports:
- port: 8002
  visibility: public
  onOpen: open-preview
- port: 9001
- port: 15672
  visibility: public
vscode:
  extensions:
    - TabNine.tabnine-vscode@3.4.14
    - felixfbecker.php-debug@1.16.0
tasks:
  - openMode: tab-after
    name: "Services"
    command: sudo sed -i 's#$GITPOD_REPO_ROOT#'$GITPOD_REPO_ROOT'#g' /etc/nginx/nginx.conf &&
             sudo sed -i 's#$GITPOD_REPO_ROOT#'$GITPOD_REPO_ROOT'#g' /etc/supervisor/conf.d/sp-php-fpm.conf &&
             service nginx start &&
             sudo cp $GITPOD_REPO_ROOT/gitpod/sp-redis.conf /etc/supervisor/conf.d/redis.conf &&
             sudo cp $GITPOD_REPO_ROOT/gitpod/sp-elasticsearch.conf /etc/supervisor/conf.d/elasticsearch.conf &&
             sudo sed -i 's/^\(\[supervisord\]\)$/\1\nnodaemon=true/' /etc/supervisor/supervisord.conf &&
             sleep 5;
             sudo /etc/init.d/supervisor start;
             sleep 15;
             sudo supervisorctl stop mysql;
             sudo mv /var/lib/mysql $GITPOD_REPO_ROOT/;
             sed -i 's#/var/lib/mysql#'$GITPOD_REPO_ROOT'/mysql#g' /etc/mysql/conf.d/mysqld.cnf;
             sudo sed -i 's#/var/lib/mysql#'$GITPOD_REPO_ROOT'/mysql#g' /etc/supervisor/conf.d/mysql.conf;
             sudo supervisorctl update;
             sudo supervisorctl reload;
             sleep 10;
             test ! -f ./gitpod/db-installed.flag && sudo ./gitpod/m2-install.sh
